### ISSUE TITLE
unable to enter the "password"

### ISSUE THREAD

**Issue by Baggette** [wawesomeNOGUI/RemoteDesktopForGaming#6]
the box where you enter the "password" is blanked out and cannot be typed into.
![image](https://user-images.githubusercontent.com/58569691/228069588-5b2db64d-90ca-4aec-891f-2186368f7829.png)

**Comment by Baggette** [comment]
oh wait im dumb, never mind I didn't read the setup thing, but not it just says checking, then is says failed and then the server seems to crash.

**Comment by Baggette** [comment]
console output:
```C:\Users\owner\Downloads\RemoteDesktopForGaming-main\RemoteDesktopForGaming-main>screenGrabWebRTC.exe -ip 0.0.0.0 -password g
Password to connect (can be changed with -password flag): g
Listening for WebRTC traffic at [::]:80
2023/03/27 16:30:45 {offer v=0
o=- 4939248672356167982 1679952645 IN IP4 0.0.0.0
s=-
t=0 0
a=fingerprint:sha-256 5C:F3:B4:17:DF:89:7A:30:A5:C6:A7:84:3C:B9:33:86:D7:61:9B:5C:BF:5A:28:0D:34:8F:75:B0:EB:02:8D:19
a=extmap-allow-mixed
a=group:BUNDLE 0 1
m=video 9 UDP/TLS/RTP/SAVPF 125
c=IN IP4 0.0.0.0
a=setup:actpass
a=mid:0
a=ice-ufrag:tdEdwfkqFFgyaosv
a=ice-pwd:pmCtDYJXplBGrdPCigKWbSmAQiUvSUxD
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:125 H264/90000
a=fmtp:125 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=ssrc:1506025221 cname:70a01578-80c3-4bbf-bdf7-ff00a010da25
a=ssrc:1506025221 msid:597d4a41-9ab1-4567-9dad-ba0d7c5117f8 ff2550a2-34d8-437c-bcc5-13625793f649
a=ssrc:1506025221 mslabel:597d4a41-9ab1-4567-9dad-ba0d7c5117f8
a=ssrc:1506025221 label:ff2550a2-34d8-437c-bcc5-13625793f649
a=msid:5ad2e14c-b84d-44bd-972c-f9413ef454cb ff2550a2-34d8-437c-bcc5-13625793f649
a=sendonly
a=candidate:842798295 1 udp 2130706431 0.0.0.0 80 typ host
a=candidate:842798295 2 udp 2130706431 0.0.0.0 80 typ host
a=end-of-candidates
m=application 9 UDP/DTLS/SCTP webrtc-datachannel
c=IN IP4 0.0.0.0
a=setup:actpass
a=mid:1
a=sendrecv
a=sctp-port:5000
a=ice-ufrag:tdEdwfkqFFgyaosv
a=ice-pwd:pmCtDYJXplBGrdPCigKWbSmAQiUvSUxD
 0xc000af2c60}
2023/03/27 16:30:45 {answer v=0
o=mozilla...THIS_IS_SDPARTA-99.0 7553047089203236759 0 IN IP4 0.0.0.0
s=-
t=0 0
a=sendrecv
a=fingerprint:sha-256 9F:13:F9:DA:E0:AB:C7:0C:9B:CE:B2:FD:DB:58:A9:C7:EC:C8:46:A8:D5:09:B4:2C:88:3D:47:14:3F:A6:5A:49
a=group:BUNDLE 0 1
a=ice-options:trickle
a=msid-semantic:WMS *
m=video 9 UDP/TLS/RTP/SAVPF 125
c=IN IP4 0.0.0.0
a=candidate:0 1 UDP 2122187007 1e5eb7e4-00df-4d3e-bfec-4ee55c9100e0.local 56954 typ host
a=recvonly
a=fmtp:125 profile-level-id=42e01f;level-asymmetry-allowed=1;packetization-mode=1
a=ice-pwd:7024987c55803a7aacdc712257eb00d8
a=ice-ufrag:851fc1a3
a=mid:0
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:125 H264/90000
a=setup:active
a=ssrc:2264306921 cname:{fdf43ec4-f78b-4510-ab50-40b13f039963}
m=application 9 UDP/DTLS/SCTP webrtc-datachannel
c=IN IP4 0.0.0.0
a=sendrecv
a=ice-pwd:7024987c55803a7aacdc712257eb00d8
a=ice-ufrag:851fc1a3
a=mid:1
a=setup:active
a=sctp-port:5000
a=max-message-size:1073741823
 <nil>} 1
x264 [info]: using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX
x264 [info]: profile High, level 4.0, 4:2:0, 8-bit
{candidate:0 1 UDP 2122187007 1e5eb7e4-00df-4d3e-bfec-4ee55c9100e0.local 56954 typ host 0xc00015f020 0xc00001cb10 0xc00015f030}
2023/03/27 16:30:45 Connection State has changed checking
{candidate:2 1 UDP 2122252543 c5b7ec0d-609d-42f6-94e4-0cbec0b5c5b3.local 56955 typ host 0xc00015f020 0xc00001cb10 0xc00015f030}
{candidate:4 1 TCP 2105458943 1e5eb7e4-00df-4d3e-bfec-4ee55c9100e0.local 9 typ host tcptype active 0xc00015f020 0xc00001cb10 0xc00015f030}
{candidate:5 1 TCP 2105524479 c5b7ec0d-609d-42f6-94e4-0cbec0b5c5b3.local 9 typ host tcptype active 0xc00015f020 0xc00001cb10 0xc00015f030}
{candidate:1 1 UDP 1685987327 50.70.231.92 56954 typ srflx raddr 0.0.0.0 rport 0 0xc00015f020 0xc00001cb10 0xc00015f030}
{ 0xc00015f020 0xc00001cb10 0xc00015f030}
2023/03/27 16:31:16 Connection State has changed failed
2023/03/27 16:31:16 Track (ID: ff2550a2-34d8-437c-bcc5-13625793f649) ended with error: io: read/write on closed pipe
x264 [info]: frame I:605   Avg QP:35.02  size: 25357
x264 [info]: mb I  I16..4: 67.0% 26.1%  6.8%
x264 [info]: 8x8 transform intra:26.1%
x264 [info]: coded y,uvDC,uvAC intra: 18.3% 10.1% 1.6%
x264 [info]: i16 v,h,dc,p: 52% 37%  8%  3%
x264 [info]: i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 12% 23% 59%  1%  1%  1%  1%  1%  3%
x264 [info]: i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 28% 25% 25%  2%  4%  4%  5%  4%  4%
x264 [info]: i8c dc,h,v,p: 78% 17%  5%  0%
x264 [info]: kb/s:5071.47
panic: send on closed channel

goroutine 26 [running]:
github.com/pion/mediadevices.(*baseTrack).unbind(0x6e0000006f?, {{0xc000ae5350, 0x20}, {{0x7ff697f96668, 0x0, 0x0}, {0xc00005c480, 0x1, 0x1}}, 0x59c41f05, ...})
        C:/Users/wsfor/go/pkg/mod/github.com/pion/mediadevices@v0.3.11/track.go:279 +0x56
github.com/pion/mediadevices.(*VideoTrack).Unbind(0x0?, {{0xc000ae5350, 0x20}, {{0x7ff697f96668, 0x0, 0x0}, {0xc00005c480, 0x1, 0x1}}, 0x59c41f05, ...})
        C:/Users/wsfor/go/pkg/mod/github.com/pion/mediadevices@v0.3.11/track.go:374 +0x58
github.com/pion/webrtc/v3.(*RTPSender).ReplaceTrack(0xc00016c480, {0x0, 0x0})
        C:/Users/wsfor/go/pkg/mod/github.com/pion/webrtc/v3@v3.1.43/rtpsender.go:248 +0x25d
github.com/pion/webrtc/v3.(*RTPSender).Stop(0xc00016c480)
        C:/Users/wsfor/go/pkg/mod/github.com/pion/webrtc/v3@v3.1.43/rtpsender.go:348 +0xaf
github.com/pion/webrtc/v3.(*RTPTransceiver).Stop(0xc00016a360)
        C:/Users/wsfor/go/pkg/mod/github.com/pion/webrtc/v3@v3.1.43/rtptransceiver.go:152 +0x7b
github.com/pion/webrtc/v3.(*PeerConnection).Close(0xc000112d80)
        C:/Users/wsfor/go/pkg/mod/github.com/pion/webrtc/v3@v3.1.43/peerconnection.go:1969 +0x1af
main.echo.func1(0x6)
        C:/Users/wsfor/go/src/github.com/wawesomeNOGUI/RemoteDesktopForGaming-main/screenGrabWebRTC.go:225 +0x94
github.com/pion/webrtc/v3.(*PeerConnection).onICEConnectionStateChange(0xc000112d80, 0xc000b85ee8?)
        C:/Users/wsfor/go/pkg/mod/github.com/pion/webrtc/v3@v3.1.43/peerconnection.go:478 +0x132
github.com/pion/webrtc/v3.(*PeerConnection).createICETransport.func1(0x5)
        C:/Users/wsfor/go/pkg/mod/github.com/pion/webrtc/v3@v3.1.43/peerconnection.go:781 +0x9b
github.com/pion/webrtc/v3.(*ICETransport).onConnectionStateChange(0xc00011a310?, 0x7ff697ab0d80?)
        C:/Users/wsfor/go/pkg/mod/github.com/pion/webrtc/v3@v3.1.43/icetransport.go:227 +0xd4
github.com/pion/webrtc/v3.(*ICETransport).Start.func1(0xc000abde60?)
        C:/Users/wsfor/go/pkg/mod/github.com/pion/webrtc/v3@v3.1.43/icetransport.go:106 +0xbf
github.com/pion/ice/v2.(*Agent).onConnectionStateChange(0xc000978dd0?, 0x0?)
        C:/Users/wsfor/go/pkg/mod/github.com/pion/ice/v2@v2.2.6/agent.go:404 +0x63
created by github.com/pion/ice/v2.(*Agent).startOnConnectionStateChangeRoutine.func2
        C:/Users/wsfor/go/pkg/mod/github.com/pion/ice/v2@v2.2.6/agent.go:430 +0x133
```

**Comment by wawesomeNOGUI** [comment]
Hi! Try running the program with the ip flag set to: 127.0.0.1 to see if you can connect from a browser window on the same computer. Also double check the ip is set in index.html

**Comment by Baggette** [comment]
> Hi! Try running the program with the ip flag set to: 127.0.0.1 to see if you can connect from a browser window on the same computer. Also double check the ip is set in index.html

ip is set in the index.html file and Ill try and use 127.0.0.0 although I don’t think it will make a difference as 0.0.0.0 just binds to all available addresses that it can, Ill try it nevertheless

**Comment by wawesomeNOGUI** [comment]
Hmm I’ll look into it, but I don’t think ICE allows 0.0.0.0 to be a candidate
